version = 0.1

[default.global.parameters]
stack_name = "workforce-dev"
region = "ap-northeast-1"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Stage=dev"
disable_rollback = false

[prod.deploy.parameters]
stack_name = "workforce-prod"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Stage=prod"
disable_rollback = false
