// THIS FILE IS GENERATED by workforce/scripts/build-skill-registry.mjs.
// DO NOT EDIT BY HAND. Run `npm run workforce:skill-registry` after
// adding, removing, or changing the executor of a skill.
//
// Source: workforce/skills/*/meta.json (executor === "deterministic")

import type { DeterministicHandler } from "./skill-types.js";

import { dispatchDiscordPing } from "../../skills/discord-ping/handler.js";

export const DETERMINISTIC_HANDLERS: Record<string, DeterministicHandler> = {
  "discord-ping": dispatchDiscordPing,
};
