// THIS FILE IS GENERATED by workforce/scripts/build-skill-registry.mjs.
// DO NOT EDIT BY HAND. Run `npm run workforce:skill-registry` after
// adding or removing a skill, or changing a skill's requires[] / commons flag.
//
// Source:
//   SKILL_REQUIRES — workforce/skills/*/meta.json (.requires[] for ALL skills,
//                    defaulting to [] when omitted; consumed by orchestrator-tick
//                    CCR batch dispatch to resolve project credentials per task)
//   COMMONS_SKILLS — workforce/skills/*/meta.json (.commons === true; Epic-021
//                    §B.1 — the baseline cadence every persona shares, discounted
//                    by the idle-talent detector in the performance-reducer walk)

export const SKILL_REQUIRES: Record<string, readonly string[]> = {
  "article-level2": ["notion.integration_token"] as const,
  "article-level3": ["notion.integration_token"] as const,
  "attention-ledger": ["workforce.feed_write_token"] as const,
  "audience-loop": ["workforce.feed_write_token"] as const,
  "backlog-reconcile": ["github.token"] as const,
  "budget-runway-review": ["workforce.feed_write_token"] as const,
  "code-task-brief": [],
  "daily-research": ["workforce.feed_write_token"] as const,
  "design-note": [],
  "discord-digest": ["discord.webhook_url"] as const,
  "discord-heartbeat": ["discord.webhook_url"] as const,
  "editorial-desk": ["workforce.feed_write_token"] as const,
  "feed-post": ["workforce.feed_write_token"] as const,
  "grid-watch": ["workforce.feed_write_token"] as const,
  "hypothesis": ["notion.integration_token"] as const,
  "india-grid-watch": ["workforce.feed_write_token"] as const,
  "issue-design": ["github.token"] as const,
  "issue-implement": ["github.token"] as const,
  "issue-triage": ["github.token"] as const,
  "legal-amendment-review-committee": ["github.token"] as const,
  "memory-curation": ["workforce.memory_write_token"] as const,
  "memory-hygiene": ["workforce.feed_write_token"] as const,
  "monthly-report": ["notion.integration_token"] as const,
  "ops-accountability-watch": ["github.token", "discord.webhook_url"] as const,
  "org-metrics-pulse": ["workforce.feed_write_token"] as const,
  "pdm-charter": [],
  "performance-refresh": ["github.token", "workforce.feed_write_token"] as const,
  "podcast-publish": ["notion.integration_token", "github.token"] as const,
  "podcast-script": ["notion.integration_token"] as const,
  "positioning-write": [],
  "pr-autopilot": ["github.token", "workforce.dispatch_token"] as const,
  "pr-remediate": ["github.token", "workforce.dispatch_token"] as const,
  "reader-signal": ["workforce.feed_write_token"] as const,
  "record-engagement": [],
  "red-team-audit": ["workforce.feed_write_token"] as const,
  "regulatory-situation-report": ["github.token"] as const,
  "research-sync": ["workforce.feed_write_token"] as const,
  "skill-maturity-report": ["workforce.feed_write_token"] as const,
  "verification-sweep": ["workforce.feed_write_token"] as const,
  "vp-monthly-report": ["notion.integration_token"] as const,
  "weekly-project-report": ["github.token"] as const,
};

/** Skills whose executions do NOT count as specialised work (Epic-021 §B.1).
 *  Generated from meta.commons so the detector never hard-codes a name list. */
export const COMMONS_SKILLS: ReadonlySet<string> = new Set([
  "daily-research",
  "feed-post",
]);
