// THIS FILE IS GENERATED by workforce/scripts/build-skill-registry.mjs.
// DO NOT EDIT BY HAND. Run `npm run workforce:skill-registry` after
// adding, removing, or changing the executor of a skill.
//
// Sources:
//   DETERMINISTIC_HANDLERS — workforce/skills/*/meta.json (executor === "deterministic")
//   SKILL_REQUIRES        — workforce/skills/*/meta.json (.requires[] for ALL skills,
//                           defaulting to [] when omitted; consumed by orchestrator-tick
//                           CCR batch dispatch to resolve project credentials per task)

import type { DeterministicHandler } from "./skill-types.js";

import { dispatchDiscordPing } from "../../skills/discord-ping/handler.js";
import { dispatchFeedHealth } from "../../skills/feed-health/handler.js";
import { dispatchPdmCharter } from "../../skills/pdm-charter/handler.js";
import { dispatchPdmDecompose } from "../../skills/pdm-decompose/handler.js";
import { dispatchPrRoute } from "../../skills/pr-route/handler.js";

export const DETERMINISTIC_HANDLERS: Record<string, DeterministicHandler> = {
  "discord-ping": dispatchDiscordPing,
  "feed-health": dispatchFeedHealth,
  "pdm-charter": dispatchPdmCharter,
  "pdm-decompose": dispatchPdmDecompose,
  "pr-route": dispatchPrRoute,
};

export const SKILL_REQUIRES: Record<string, readonly string[]> = {
  "article-draft": [],
  "article-level2": ["notion.integration_token@l1", "notion.integration_token@l2"] as const,
  "code-task-brief": [],
  "design-note": [],
  "discord-heartbeat": ["discord.webhook_url"] as const,
  "discord-ping": [],
  "feed-health": [],
  "feed-post": ["workforce.feed_write_token"] as const,
  "market-research": [],
  "pdm-charter": [],
  "pdm-decompose": [],
  "plan-write": [],
  "positioning-write": [],
  "pr-route": ["github.token"] as const,
};
